// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const users = `-- name: users :exec
INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE)
VALUES($1,$2,$3,$4,$5)
`

type usersParams struct {
	FirstName string         `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     sql.NullString `json:"email"`
	Password  string         `json:"password"`
	Role      UserRole       `json:"role"`
}

func (q *Queries) users(ctx context.Context, arg usersParams) error {
	_, err := q.db.ExecContext(ctx, users,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	return err
}
